import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,rm,readdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';
import {createTransactionInbox} from '../shared-transaction-inbox.mjs';
const proof={bundleId:'com.liuzhigang.NutriScan',productId:'com.liuzhigang.nutriscan.pro.monthlya',type:'Auto-Renewable Subscription',environment:'Production',transactionId:'id/../escape',originalTransactionId:'original',purchaseDate:Date.now()-1000,price:4990,currency:'USD'};
async function fixture(t){const directory=await mkdtemp(join(tmpdir(),'shared-inbox-'));t.after(()=>rm(directory,{recursive:true,force:true}));const options={directory,certDirectory:resolve('certs')};return {options,service:createTransactionInbox(options)}}
test('NutriScan persists separately, filenames cannot traverse, duplicates survive restart',async t=>{const f=await fixture(t);const r=await f.service.recordVerified('nutriscan',proof,'signed');assert.equal(r.commission_eligible,false);assert.equal((await createTransactionInbox(f.options).recordVerified('nutriscan',proof,'signed')).duplicate,true);assert.equal((await readdir(join(f.options.directory,'partner-inbox','nutriscan','Production'))).length,1);assert.deepEqual(await readdir(f.options.directory),['partner-inbox']);});
test('Refund stays revoked after old receipt replay; sandbox is isolated',async t=>{const f=await fixture(t);await f.service.recordVerified('nutriscan',proof,'refund',{refund:true});assert.equal((await f.service.recordVerified('nutriscan',proof,'old')).revoked,true);assert.equal((await f.service.recordVerified('nutriscan',{...proof,environment:'Sandbox'},'sandbox')).revoked,false)});
test('Foreign products, changed owner or amount, and invalid dates are rejected',async t=>{const f=await fixture(t);await f.service.recordVerified('nutriscan',proof,'signed');for(const patch of [{bundleId:'com.liuzhigang.AI-Live-Streaming'},{productId:'coins'},{appAccountToken:'someone'},{price:100},{purchaseDate:0}])await assert.rejects(f.service.recordVerified('nutriscan',{...proof,...patch},'wrong'));await assert.rejects(f.service.recordVerified('../squadlive',proof,'wrong'));});
test('Missing persistent storage and forged Apple signatures fail closed',async t=>{const f=await fixture(t);await assert.rejects(createTransactionInbox({...f.options,directory:undefined}).recordVerified('nutriscan',proof,'signed'),/storage/);await assert.rejects(f.service.receive('nutriscan','transactions','x'.repeat(150)),/signature/);assert.equal((await readdir(f.options.directory)).length,0);});
